# -*- coding: utf-8 -*-
"""G3MINOR1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEfnpF1YxNrhUkU94Qf4TgSie7O1WNaI
"""

-------------------------------------pip install split-folders

import splitfolders

# Run this cell if u can't mount ur drive automatically

from google.colab import drive
drive.mount('/content/drive')

#set the directory
input_file = '/content/drive/My Drive/appledata/'
output_file = '/content/drive/MyDrive/appledata splittedfinal'

splitfolders.ratio(input_file, output=output_file, seed=38, ratio=(0.70, 0.15, 0.15), group_prefix=None)

#set the directory
input_file = '/content/drive/My Drive/appledata_augumented/'
output_file = '/content/drive/MyDrive/appledata_augumented_splitted'

splitfolders.ratio(input_file, output=output_file, seed=38, ratio=(0.70, 0.15, 0.15), group_prefix=None)



